// The sources of the weekly Management Review, shared by the issues: an issue names the ones it uses, by id, in
// its own order. Each figure was checked against its source first (docs/revista/management-review-nr-XX.md).
// "via" names the independent summary a figure was checked against when the publisher's own page could not be
// opened; the issue says so beside the source. A source without an address is cited by title and date only.
export const sources = [
  {
    id: "rework-managers",
    title: "Following the data: The research behind great managers",
    by: "Google re:Work",
    year: 2018,
    url: "https://rework.withgoogle.com/intl/en/guides/following-the-data-the-research-behind-great-managers",
  },
  {
    id: "garvin-2013",
    title: "How Google Sold Its Engineers on Management",
    by: "David A. Garvin, Harvard Business Review",
    year: 2013,
    url: "https://hbr.org/2013/12/how-google-sold-its-engineers-on-management",
  },
  {
    id: "bryant-2011",
    title: "Google's Quest to Build a Better Boss",
    by: "Adam Bryant, The New York Times",
    year: 2011,
  },
  {
    id: "quartz-2017",
    title: "Manager feedback at Google: employees are asked 13 questions about their bosses",
    by: "Quartz",
    year: 2017,
    url: "https://qz.com/1058760/manager-feedback-at-google-employees-are-asked-13-questions-about-their-bosses-as-part-of-a-semi-annual-review-goog-googl",
  },
  {
    id: "bock-2015",
    title: "Work Rules!",
    by: "Laszlo Bock",
    year: 2015,
    via: "World Economic Forum, 2015",
    url: "https://www.weforum.org/stories/2015/04/the-9-habits-of-the-best-managers-according-to-googles-hr-boss/",
  },
  {
    id: "gallup-manager-2015",
    title: "State of the American Manager",
    by: "Gallup",
    year: 2015,
    url: "https://www.gallup.com/services/182138/state-american-manager.aspx",
  },
  {
    id: "gallup-rare-2014",
    title: "Why Great Managers Are So Rare",
    by: "Randall Beck & Jim Harter, Gallup",
    year: 2014,
    url: "https://www.gallup.com/workplace/231593/why-great-managers-so-rare.aspx",
  },
  {
    id: "gallup-sogw-2026",
    title: "State of the Global Workplace 2026",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/349484/state-of-the-global-workplace.aspx",
  },
  // No. 2
  {
    id: "osha-2019",
    title: "Using Leading Indicators to Improve Safety and Health Outcomes",
    by: "OSHA",
    year: 2019,
    url: "https://www.osha.gov/sites/default/files/OSHA_Leading_Indicators.pdf",
  },
  {
    id: "kaplan-norton-1992",
    title: "The Balanced Scorecard: Measures That Drive Performance",
    by: "Robert S. Kaplan & David P. Norton, Harvard Business Review",
    year: 1992,
  },
  {
    id: "kaplan-norton-1996",
    title: "Using the Balanced Scorecard as a Strategic Management System",
    by: "Robert S. Kaplan & David P. Norton, Harvard Business Review",
    year: 1996,
  },
  {
    id: "mitsmr-bcg-2024",
    title: "The Future of Strategic Measurement: Enhancing KPIs With AI",
    by: "MIT Sloan Management Review & BCG",
    year: 2024,
    url: "https://sloanreview.mit.edu/projects/the-future-of-strategic-measurement-enhancing-kpis-with-ai",
  },
  {
    id: "mitsmr-google-2018",
    title: "Leading With Next-Generation Key Performance Indicators",
    by: "MIT Sloan Management Review & Google",
    year: 2018,
    url: "https://sloanreview.mit.edu/projects/leading-with-next-generation-key-performance-indicators",
  },
  {
    id: "goodhart-1975",
    title: "Problems of Monetary Management: The U.K. Experience",
    by: "Charles Goodhart",
    year: 1975,
  },
  {
    id: "strathern-1997",
    title: "\u2018Improving ratings\u2019: audit in the British University system",
    by: "Marilyn Strathern, European Review",
    year: 1997,
    url: "https://www.cambridge.org/core/journals/european-review/article/improving-ratings-audit-in-the-british-university-system/FC2EE640C0C44E3DB87C29FB666E9AAB",
  },
  // No. 3
  {
    id: "sull-yoder-2018",
    title: "No One Knows Your Strategy \u2014 Not Even Your Top Leaders",
    by: "Charles Sull, Donald Sull & James Yoder, MIT Sloan Management Review",
    year: 2018,
    url: "https://sloanreview.mit.edu/?p=55347",
  },
  {
    id: "sull-homkes-2015",
    title: "Why Strategy Execution Unravels\u2014and What to Do About It",
    by: "Donald Sull, Rebecca Homkes & Charles Sull, Harvard Business Review",
    year: 2015,
    url: "https://hbr.org/2015/03/why-strategy-execution-unravels-and-what-to-do-about-it",
  },
  {
    id: "lbs-2015",
    title: "Two thirds of senior managers can\u2019t name their firm\u2019s top priorities",
    by: "London Business School (Rebecca Homkes & Donald Sull)",
    year: 2015,
    url: "https://www.london.edu/news/two-thirds-of-senior-managers-cant-name-their-firms-top-priorities",
  },
  {
    id: "leinwand-2015",
    title: "Only 8% of Leaders Are Good at Both Strategy and Execution",
    by: "Paul Leinwand, Cesare Mainardi & Art Kleiner, Harvard Business Review",
    year: 2015,
    url: "https://hbr.org/2015/12/only-8-of-leaders-are-good-at-both-strategy-and-execution",
  },
  // No. 4
  {
    id: "edmondson-1999",
    title: "Psychological Safety and Learning Behavior in Work Teams",
    by: "Amy Edmondson, Administrative Science Quarterly",
    year: 1999,
    url: "https://doi.org/10.2307/2666999",
  },
  {
    id: "edmondson-1996",
    title: "Learning from Mistakes Is Easier Said Than Done",
    by: "Amy Edmondson, Journal of Applied Behavioral Science",
    year: 1996,
    url: "https://doi.org/10.1177/0021886396321001",
  },
  {
    id: "rework-teams",
    title: "Understand team effectiveness (Project Aristotle)",
    by: "Google re:Work",
    year: 2015,
    url: "https://rework.withgoogle.com/intl/en/guides/understand-team-effectiveness",
  },
  {
    id: "frazier-2017",
    title: "Psychological Safety: A Meta-Analytic Review and Extension",
    by: "M. Lance Frazier, Stav Fainshmidt, Ryan L. Klinger, Amir Pezeshkan & Veselina Vracheva, Personnel Psychology",
    year: 2017,
    url: "https://doi.org/10.1111/peps.12183",
  },
  {
    id: "mckinsey-2021",
    title: "Psychological safety and the critical role of leadership development",
    by: "McKinsey & Company",
    year: 2021,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/psychological-safety-and-the-critical-role-of-leadership-development",
  },
  {
    id: "edmondson-2018",
    title: "The Fearless Organization",
    by: "Amy C. Edmondson",
    year: 2018,
  },
  // No. 5
  {
    id: "ohno-1988",
    title: "Toyota Production System: Beyond Large-Scale Production",
    by: "Taiichi Ohno",
    year: 1988,
  },
  {
    id: "lei-lexicon",
    title: "Lean Lexicon: seven wastes",
    by: "Lean Enterprise Institute",
    year: 2014,
    url: "https://www.lean.org/lexicon-terms/seven-wastes/",
  },
  {
    id: "lei-eight-wastes",
    title: "The Eight Wastes of Lean",
    by: "Lean Enterprise Institute, The Lean Post",
    year: 2020,
    url: "https://www.lean.org/the-lean-post/articles/the-eight-wastes-of-lean/",
  },
  {
    id: "liker-2004",
    title: "The Toyota Way",
    by: "Jeffrey K. Liker",
    year: 2004,
  },
  {
    id: "womack-jones-1996",
    title: "Lean Thinking",
    by: "James P. Womack & Daniel T. Jones",
    year: 1996,
    via: "Lean Enterprise Institute, Seeing the Whole",
    url: "https://www.lean.org/wp-content/uploads/2021/01/seeing-the-whole-introduction.pdf",
  },
  {
    id: "krafcik-1988",
    title: "Triumph of the Lean Production System",
    by: "John F. Krafcik, Sloan Management Review",
    year: 1988,
  },
  {
    id: "womack-1990",
    title: "The Machine That Changed the World",
    by: "James P. Womack, Daniel T. Jones & Daniel Roos",
    year: 1990,
  },
  // No. 6
  {
    id: "peter-hull-1969",
    title: "The Peter Principle",
    by: "Laurence J. Peter & Raymond Hull",
    year: 1969,
  },
  {
    id: "benson-li-shue-2019",
    title: "Promotions and the Peter Principle",
    by: "Alan Benson, Danielle Li & Kelly Shue, Quarterly Journal of Economics",
    year: 2019,
    url: "https://www.nber.org/papers/w24343",
  },
  {
    id: "gallup-supervisors-2026",
    title: "When Good Frontline Workers Make Bad Supervisors",
    by: "Corey Tatel & Andy Stewart, Gallup",
    year: 2026,
    via: "HR Dive",
    url: "https://www.gallup.com/workplace/700163/when-good-frontline-workers-make-bad-supervisors.aspx",
  },
  {
    id: "charan-2001",
    title: "The Leadership Pipeline",
    by: "Ram Charan, Stephen Drotter & James Noel",
    year: 2001,
  },
  {
    id: "hill-2007",
    title: "Becoming the Boss",
    by: "Linda A. Hill, Harvard Business Review",
    year: 2007,
    url: "https://hbr.org/2007/01/becoming-the-boss",
  },
  // No. 7
  {
    id: "locke-latham-2002",
    title: "Building a Practically Useful Theory of Goal Setting and Task Motivation",
    by: "Edwin A. Locke & Gary P. Latham, American Psychologist",
    year: 2002,
    url: "https://doi.org/10.1037/0003-066X.57.9.705",
  },
  {
    id: "doran-1981",
    title: "There's a S.M.A.R.T. way to write management's goals and objectives",
    by: "George T. Doran, Management Review",
    year: 1981,
  },
  {
    id: "ordonez-2009",
    title: "Goals Gone Wild: The Systematic Side Effects of Overprescribing Goal Setting",
    by: "Lisa D. Ordóñez, Maurice E. Schweitzer, Adam D. Galinsky & Max H. Bazerman",
    year: 2009,
    url: "https://repository.upenn.edu/mgmt_papers/325",
  },
  {
    id: "locke-latham-2009",
    title: "Has Goal Setting Gone Wild, or Have Its Attackers Abandoned Good Scholarship?",
    by: "Edwin A. Locke & Gary P. Latham, Academy of Management Perspectives",
    year: 2009,
  },
  {
    id: "mcchesney-2012",
    title: "The 4 Disciplines of Execution",
    by: "Chris McChesney, Sean Covey & Jim Huling",
    year: 2012,
    via: "FranklinCovey, Discipline 1",
    url: "https://www.franklincovey.com/courses/the-4-disciplines/discipline-1-wildly-important/",
  },
  {
    id: "gallup-us-2026",
    title: "Employee Engagement Declines From 2020 Peak",
    by: "Jim Harter, Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/701486/employee-engagement-declines-2020-peak.aspx",
  },
  {
    id: "gallup-indicator",
    title: "Indicator: Employee Engagement",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/394373/indicator-employee-engagement.aspx",
  },
  // No. 8
  {
    id: "mckinsey-2019-decisions",
    title: "Decision making in the age of urgency",
    by: "McKinsey & Company",
    year: 2019,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/decision-making-in-the-age-of-urgency",
  },
  {
    id: "mckinsey-2019-three-keys",
    title: "Three keys to faster, better decisions",
    by: "McKinsey Quarterly",
    year: 2019,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/three-keys-to-faster-better-decisions",
  },
  {
    id: "desmet-2017",
    title: "Untangling your organization's decision making",
    by: "Aaron De Smet, Gerald Lackey & Leigh M. Weiss, McKinsey Quarterly",
    year: 2017,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/untangling-your-organizations-decision-making",
  },
  {
    id: "rogers-blenko-2006",
    title: "Who Has the D? How Clear Decision Roles Enhance Organizational Performance",
    by: "Paul Rogers & Marcia Blenko, Harvard Business Review",
    year: 2006,
    url: "https://hbr.org/2006/01/who-has-the-d-how-clear-decision-roles-enhance-organizational-performance",
  },
  // No. 9
  {
    id: "gallup-albania-2026",
    title: "State of the Global Workplace: Albania",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/704378/state-global-workplace-albania-country-level-data.aspx",
  },
  {
    id: "gallup-germany-2026",
    title: "State of the Global Workplace: Germany",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/705434/state-global-workplace-germany-country-level-data.aspx",
  },
  {
    id: "gallup-q12-2024",
    title: "The Relationship Between Engagement at Work and Organizational Outcomes: 2024 Q12 Meta-Analysis",
    by: "James K. Harter et al., Gallup",
    year: 2024,
    url: "https://www.gallup.com/workplace/321725/q12-meta-analysis-report.aspx",
  },
  {
    id: "gallup-q12",
    title: "Gallup's Employee Engagement Survey: Ask the Right Questions With the Q12 Survey",
    by: "Gallup",
    year: 2026,
    url: "https://q12.gallup.com/",
  },
  // No. 10
  {
    id: "metr-2025",
    title: "Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity",
    by: "METR",
    year: 2025,
    url: "https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/",
  },
  {
    id: "gallup-ai-2025",
    title: "AI Use at Work Has Nearly Doubled in Two Years",
    by: "Gallup",
    year: 2025,
    url: "https://www.gallup.com/workplace/691643/work-nearly-doubled-two-years.aspx",
  },
  {
    id: "gallup-ai-q4-2025",
    title: "Frequent Use of AI in the Workplace Continued to Rise in Q4",
    by: "Andy Kemp, Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/701195/frequent-workplace-continued-rise.aspx",
  },
  {
    id: "gallup-ai-indicator",
    title: "Indicator: Artificial Intelligence",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/699797/indicator-artificial-intelligence.aspx",
  },
  {
    id: "gallup-ai-engagement-2026",
    title: "Employee Engagement Remains Flat as AI Adoption Accelerates",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/712433/employee-engagement-remains-flat-adoption-accelerates.aspx",
  },
  {
    id: "dellacqua-2023",
    title: "Navigating the Jagged Technological Frontier",
    by: "Fabrizio Dell'Acqua, Edward McFowland III, Ethan Mollick et al., Harvard Business School",
    year: 2023,
    url: "https://papers.ssrn.com/abstract=4573321",
  },
  {
    id: "brynjolfsson-2023",
    title: "Generative AI at Work",
    by: "Erik Brynjolfsson, Danielle Li & Lindsey Raymond, NBER",
    year: 2023,
    url: "https://www.nber.org/papers/w31161",
  },
  {
    id: "microsoft-wti-2026",
    title: "Agents, human agency, and the opportunity for every organization",
    by: "Microsoft, Work Trend Index",
    year: 2026,
    url: "https://www.microsoft.com/en-us/worklab/work-trend-index/agents-human-agency-and-the-opportunity-for-every-organization",
  },
  {
    id: "workslop-2025",
    title: "AI-Generated “Workslop” Is Destroying Productivity",
    by: "Kate Niederhoffer et al., Harvard Business Review",
    year: 2025,
    url: "https://hbr.org/2025/09/ai-generated-workslop-is-destroying-productivity",
  },
  {
    id: "nanda-2025",
    title: "The GenAI Divide: State of AI in Business 2025",
    by: "Aditya Challapally et al., MIT NANDA",
    year: 2025,
  },
  // No. 11
  {
    id: "rework-grow",
    title: "Coach using the GROW model",
    by: "Google re:Work",
    year: 2026,
    url: "https://rework.withgoogle.com/intl/en/guides/coach-using-the-grow-model",
  },
  {
    id: "whitmore-1992",
    title: "Coaching for Performance",
    by: "John Whitmore",
    year: 1992,
  },
  {
    id: "gallup-habit",
    title: "A Great Manager's Most Important Habit",
    by: "Gallup",
    year: 2023,
    url: "https://www.gallup.com/workplace/505370/great-manager-important-habit.aspx",
  },
  {
    id: "clifton-harter-2019",
    title: "It's the Manager: Moving From Boss to Coach",
    by: "Jim Clifton & Jim Harter, Gallup Press",
    year: 2019,
    url: "https://www.gallup.com/itsthemanager/",
  },
  {
    id: "gallup-conversations-2020",
    title: "5 Coaching Conversations (Called to Coach)",
    by: "Gallup",
    year: 2020,
    url: "https://www.gallup.com/cliftonstrengths/en/296192/coaching-conversations-role-relationship-orientation.aspx",
  },
  {
    id: "jones-2016",
    title: "The effectiveness of workplace coaching: a meta-analysis of learning and performance outcomes from coaching",
    by: "Rebecca J. Jones, Stephen A. Woods & Yves R. F. Guillaume, Journal of Occupational and Organizational Psychology",
    year: 2016,
    url: "https://doi.org/10.1111/joop.12119",
  },
  {
    id: "theeboom-2014",
    title: "Does coaching work? A meta-analysis on the effects of coaching on individual level outcomes in an organizational context",
    by: "Tim Theeboom, Bianca Beersma & Annelies E. M. van Vianen, Journal of Positive Psychology",
    year: 2014,
    url: "https://doi.org/10.1080/17439760.2013.837499",
  },
  // No. 12
  {
    id: "grove-1983",
    title: "High Output Management",
    by: "Andrew S. Grove",
    year: 1983,
  },
  {
    id: "doerr-2018",
    title: "Measure What Matters",
    by: "John Doerr",
    year: 2018,
    url: "https://www.penguinrandomhouse.com/books/546304/measure-what-matters-by-john-doerr-foreword-by-larry-page/",
  },
  {
    id: "doerr-ted-2018",
    title: "Why the secret to success is setting the right goals",
    by: "John Doerr, TED",
    year: 2018,
    url: "https://www.ted.com/talks/john_doerr_why_the_secret_to_success_is_setting_the_right_goals",
  },
  {
    id: "rework-okr",
    title: "Set goals with OKRs",
    by: "Google re:Work",
    year: 2016,
    url: "https://rework.withgoogle.com/intl/en/guides/set-goals-with-okrs",
  },
  {
    id: "klau-2013",
    title: "How Google sets goals: OKRs",
    by: "Rick Klau, Google Ventures",
    year: 2013,
    url: "https://library.gv.com/how-google-sets-goals-okrs-a1f69b0b72c7",
  },
  {
    id: "silva-santos-2024",
    title: "Surveying the Academic Literature on the Use of OKR (Objectives and Key Results) – An Update",
    by: "Roberto Silva & Gleison Santos, iSys",
    year: 2024,
    url: "https://journals-sol.sbc.org.br/index.php/isys/article/view/3885",
  },
  {
    id: "butler-2024",
    title: "Objectives and Key Results in Software Teams: Challenges, Opportunities and Impact on Development",
    by: "Jenna Butler, Thomas Zimmermann & Christian Bird, ICSE-SEIP",
    year: 2024,
    url: "https://arxiv.org/abs/2311.00236",
  },
  // No. 13
  {
    id: "perlow-2017",
    title: "Stop the Meeting Madness",
    by: "Leslie A. Perlow, Constance Noonan Hadley & Eunice Eun, Harvard Business Review",
    year: 2017,
    url: "https://hbr.org/2017/07/stop-the-meeting-madness",
  },
  {
    id: "mankins-2014",
    title: "Your Scarcest Resource",
    by: "Michael Mankins, Chris Brahm & Gregory Caimi, Harvard Business Review",
    year: 2014,
    url: "https://hbr.org/2014/05/your-scarcest-resource",
  },
  {
    id: "bluedorn-1999",
    title: "The effects of stand-up and sit-down meeting formats on meeting outcomes",
    by: "Allen C. Bluedorn, Daniel B. Turban & Mary Sue Love, Journal of Applied Psychology",
    year: 1999,
    url: "https://doi.org/10.1037/0021-9010.84.2.277",
  },
  {
    id: "microsoft-workday-2025",
    title: "Breaking down the infinite workday",
    by: "Microsoft, Work Trend Index",
    year: 2025,
    url: "https://www.microsoft.com/en-us/worklab/work-trend-index/breaking-down-infinite-workday",
  },
  {
    id: "lencioni-2004",
    title: "Death by Meeting",
    by: "Patrick Lencioni",
    year: 2004,
  },
  {
    id: "laker-2022",
    title: "The Surprising Impact of Meeting-Free Days",
    by: "Benjamin Laker, Vijay Pereira, Pawan Budhwar & Ashish Malik, MIT Sloan Management Review",
    year: 2022,
    url: "https://sloanreview.mit.edu/article/the-surprising-impact-of-meeting-free-days/",
  },
  // No. 14
  {
    id: "gallup-turnover-2024",
    title: "42% of Employee Turnover Is Preventable but Often Ignored",
    by: "Corey Tatel & Ben Wigert, Gallup",
    year: 2024,
    url: "https://www.gallup.com/workplace/646538/employee-turnover-preventable-often-ignored.aspx",
  },
  {
    id: "gallup-turnover-2019",
    title: "This Fixable Problem Costs U.S. Businesses $1 Trillion",
    by: "Shane McFeely & Ben Wigert, Gallup",
    year: 2019,
    url: "https://www.gallup.com/workplace/247391/fixable-problem-costs-businesses-trillion.aspx",
  },
  {
    id: "mckinsey-attrition-2021",
    title: "'Great Attrition' or 'Great Attraction'? The choice is yours",
    by: "Aaron De Smet et al., McKinsey Quarterly",
    year: 2021,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/great-attrition-or-great-attraction-the-choice-is-yours",
  },
  {
    id: "mckinsey-attrition-2022",
    title: "The Great Attrition is making hiring harder. Are you searching the right talent pools?",
    by: "McKinsey & Company",
    year: 2022,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/the-great-attrition-is-making-hiring-harder-are-you-searching-the-right-talent-pools",
  },
  {
    id: "mitchell-2001",
    title: "Why people stay: Using job embeddedness to predict voluntary turnover",
    by: "Terence R. Mitchell et al., Academy of Management Journal",
    year: 2001,
    url: "https://doi.org/10.5465/3069391",
  },
  {
    id: "lee-1999",
    title: "The unfolding model of voluntary turnover: A replication and extension",
    by: "Thomas W. Lee et al., Academy of Management Journal",
    year: 1999,
    url: "https://doi.org/10.5465/257015",
  },
  {
    id: "boushey-glynn-2012",
    title: "There Are Significant Business Costs to Replacing Employees",
    by: "Heather Boushey & Sarah Jane Glynn, Center for American Progress",
    year: 2012,
    url: "https://www.americanprogress.org/article/there-are-significant-business-costs-to-replacing-employees/",
  },
  {
    id: "bls-jolts-2026",
    title: "Job Openings and Labor Turnover – August 2026",
    by: "U.S. Bureau of Labor Statistics",
    year: 2026,
    url: "https://www.bls.gov/news.release/archives/jolts_09292026.htm",
  },
  // No. 15
  {
    id: "juran-1974",
    title: "The Non-Pareto Principle; Mea Culpa",
    by: "Joseph M. Juran, Juran Institute",
    year: 1974,
    url: "https://www.juran.com/wp-content/uploads/2021/03/The-Non-Pareto-Principle-1974.pdf",
  },
  {
    id: "asq-pareto",
    title: "What is a Pareto Chart?",
    by: "ASQ",
    year: 2026,
    url: "https://asq.org/quality-resources/pareto",
  },
  {
    id: "lei-a3",
    title: "Lean Lexicon: A3 report",
    by: "Lean Enterprise Institute",
    year: 2014,
    url: "https://www.lean.org/lexicon-terms/a3-report/",
  },
  {
    id: "shook-2009",
    title: "Toyota's Secret: The A3 Report",
    by: "John Shook, MIT Sloan Management Review",
    year: 2009,
    url: "https://sloanreview.mit.edu/article/toyotas-secret-the-a3-report/",
  },
  {
    id: "toyota-tbp",
    title: "75 Years of Toyota: Toyota Business Practices",
    by: "Toyota Motor Corporation",
    year: 2012,
    url: "https://www.toyota-global.com/company/history_of_toyota/75years/text/leaping_forward_as_a_global_corporation/chapter4/section7/item4_a.html",
  },
  {
    id: "tucker-edmondson-2003",
    title: "Why Hospitals Don't Learn from Failures",
    by: "Anita L. Tucker & Amy C. Edmondson, California Management Review",
    year: 2003,
    url: "https://cmr.berkeley.edu/2003/02/45-2-why-hospitals-dont-learn-from-failures-organizational-and-psychological-dynamics-that-inhibit-system-change",
  },
  {
    id: "hse-accidents-2025",
    title: "Kinds of accident statistics in Great Britain, 2025",
    by: "Health and Safety Executive",
    year: 2025,
    url: "https://www.hse.gov.uk/statistics/causinj/index.htm",
  },
  {
    id: "ghosh-sobek-2015",
    title: "A problem-solving routine for improving hospital operations",
    by: "M. Ghosh & D. K. Sobek II, Journal of Health Organization and Management",
    year: 2015,
    url: "https://doi.org/10.1108/JHOM-09-2013-0191",
  },
  // No. 16
  {
    id: "birkinshaw-cohen-2013",
    title: "Make Time for the Work That Matters",
    by: "Julian Birkinshaw & Jordan Cohen, Harvard Business Review",
    year: 2013,
    url: "https://hbr.org/2013/09/make-time-for-the-work-that-matters",
  },
  {
    id: "gallup-delegator-2015",
    title: "Delegating: A Huge Management Challenge for Entrepreneurs",
    by: "Sangeeta Bharadwaj Badal & Bryant Ott, Gallup",
    year: 2015,
    url: "https://news.gallup.com/businessjournal/182414/delegating-huge-management-challenge-entrepreneurs.aspx",
  },
  {
    id: "oncken-wass-1974",
    title: "Management Time: Who's Got the Monkey?",
    by: "William Oncken Jr. & Donald L. Wass, Harvard Business Review",
    year: 1974,
    url: "https://hbr.org/1999/11/management-time-whos-got-the-monkey",
  },
  {
    id: "leana-1986",
    title: "Predictors and Consequences of Delegation",
    by: "Carrie R. Leana, Academy of Management Journal",
    year: 1986,
    url: "https://doi.org/10.5465/255943",
  },
  {
    id: "yukl-fu-1999",
    title: "Determinants of delegation and consultation by managers",
    by: "Gary Yukl & Ping Ping Fu, Journal of Organizational Behavior",
    year: 1999,
  },
  {
    id: "lee-willis-tian-2018",
    title: "Empowering leadership: A meta-analytic examination of incremental contribution, mediation, and moderation",
    by: "Allan Lee, Sara Willis & Amy Wei Tian, Journal of Organizational Behavior",
    year: 2018,
    url: "https://doi.org/10.1002/job.2220",
  },
  {
    id: "cheong-2016",
    title: "Two faces of empowering leadership: Enabling and burdening",
    by: "Minyoung Cheong et al., The Leadership Quarterly",
    year: 2016,
    url: "https://doi.org/10.1016/j.leaqua.2016.01.006",
  },
  {
    id: "bloom-2012",
    title: "The Organization of Firms Across Countries",
    by: "Nicholas Bloom, Raffaella Sadun & John Van Reenen, Quarterly Journal of Economics",
    year: 2012,
    url: "https://ideas.repec.org/a/oup/qjecon/v127y2012i4p1663-1705.html",
  },
  // No. 17
  {
    id: "kaplan-2010",
    title: "Conceptual Foundations of the Balanced Scorecard",
    by: "Robert S. Kaplan, Harvard Business School",
    year: 2010,
    url: "https://ideas.repec.org/p/hbs/wpaper/10-074.html",
  },
  {
    id: "kaplan-norton-2000",
    title: "Having Trouble with Your Strategy? Then Map It",
    by: "Robert S. Kaplan & David P. Norton, Harvard Business Review",
    year: 2000,
    url: "https://hbr.org/2000/09/having-trouble-with-your-strategy-then-map-it",
  },
  {
    id: "bain-2007",
    title: "Management Tools and Trends 2007",
    by: "Darrell Rigby & Barbara Bilodeau, Bain & Company",
    year: 2007,
    url: "https://www.bain.cn/pdfs/200906150356217586.pdf",
  },
  {
    id: "davis-albright-2004",
    title: "An investigation of the effect of Balanced Scorecard implementation on financial performance",
    by: "S. Davis & T. Albright, Management Accounting Research",
    year: 2004,
    url: "https://doi.org/10.1016/j.mar.2003.11.001",
  },
  {
    id: "tawse-tabesh-2023",
    title: "Thirty years with the balanced scorecard: What we have learned",
    by: "Alex Tawse & Pooya Tabesh, Business Horizons",
    year: 2023,
    url: "https://doi.org/10.1016/j.bushor.2022.03.005",
  },
  {
    id: "ittner-2003",
    title: "Subjectivity and the weighting of performance measures: Evidence from a balanced scorecard",
    by: "Christopher D. Ittner et al., The Accounting Review",
    year: 2003,
  },
  {
    id: "lipe-salterio-2000",
    title: "The balanced scorecard: Judgmental effects of common and unique performance measures",
    by: "Marlys G. Lipe & Steven E. Salterio, The Accounting Review",
    year: 2000,
  },
  {
    id: "norreklit-2000",
    title: "The balance on the balanced scorecard: a critical analysis of some of its assumptions",
    by: "Hanne Nørreklit, Management Accounting Research",
    year: 2000,
    url: "https://doi.org/10.1006/mare.1999.0121",
  },
  // No. 18
  {
    id: "mintzberg-1975",
    title: "The Manager's Job: Folklore and Fact",
    by: "Henry Mintzberg, Harvard Business Review",
    year: 1975,
    url: "https://hbr.org/1990/03/the-managers-job-folklore-and-fact",
  },
  {
    id: "porter-nohria-2018",
    title: "How CEOs Manage Time",
    by: "Michael E. Porter & Nitin Nohria, Harvard Business Review",
    year: 2018,
    url: "https://hbr.org/2018/07/how-ceos-manage-time",
  },
  {
    id: "mann-2005",
    title: "Creating a Lean Culture: Tools to Sustain Lean Conversions",
    by: "David Mann, Productivity Press",
    year: 2005,
  },
  {
    id: "mann-2006",
    title: "Creating a Lean Culture That Lasts: A Conversation with David Mann",
    by: "Mark Graban, Lean Blog Podcast",
    year: 2006,
    url: "https://www.leanblog.org/2006/11/creating-a-lean-culture-david-mann/",
  },
  {
    id: "goldenhar-2013",
    title: "Huddling for high reliability and situation awareness",
    by: "Linda M. Goldenhar et al., BMJ Quality & Safety",
    year: 2013,
    url: "https://pubmed.ncbi.nlm.nih.gov/23744537/",
  },
  {
    id: "brady-2013",
    title: "Improving situation awareness to reduce unrecognized clinical deterioration and serious safety events",
    by: "Patrick W. Brady et al., Pediatrics",
    year: 2013,
    url: "https://pubmed.ncbi.nlm.nih.gov/23230078/",
  },
  // No. 19
  {
    id: "kluger-denisi-1996",
    title: "The effects of feedback interventions on performance",
    by: "Avraham N. Kluger & Angelo DeNisi, Psychological Bulletin",
    year: 1996,
    url: "https://doi.org/10.1037/0033-2909.119.2.254",
  },
  {
    id: "buckingham-goodall-2015",
    title: "Reinventing Performance Management",
    by: "Marcus Buckingham & Ashley Goodall, Harvard Business Review",
    year: 2015,
    url: "https://hbr.org/2015/04/reinventing-performance-management",
  },
  {
    id: "scullen-2000",
    title: "Understanding the latent structure of job performance ratings",
    by: "Steven E. Scullen, Michael K. Mount & Maynard Goff, Journal of Applied Psychology",
    year: 2000,
    url: "https://doi.org/10.1037/0021-9010.85.6.956",
  },
  {
    id: "gallup-reviews-2019",
    title: "More Harm Than Good: The Truth About Performance Reviews",
    by: "Ryan Sutton & Ben Wigert, Gallup",
    year: 2019,
    url: "https://www.gallup.com/workplace/249332/harm-good-truth-performance-reviews.aspx",
  },
  {
    id: "ccl-sbi",
    title: "Situation-Behavior-Impact (SBI) feedback",
    by: "Center for Creative Leadership",
    year: 2026,
    url: "https://www.ccl.org/situation-behavior-impact/",
  },
  {
    id: "wisniewski-2020",
    title: "The Power of Feedback Revisited: A Meta-Analysis of Educational Feedback Research",
    by: "Benedikt Wisniewski, Klaus Zierer & John Hattie, Frontiers in Psychology",
    year: 2020,
    url: "https://doi.org/10.3389/fpsyg.2019.03087",
  },
  {
    id: "anseel-2015",
    title: "How Are We Doing After 30 Years? A Meta-Analytic Review of the Antecedents and Outcomes of Feedback-Seeking Behavior",
    by: "Frederik Anseel et al., Journal of Management",
    year: 2015,
    url: "https://doi.org/10.1177/0149206313484521",
  },
  // No. 20
  {
    id: "kahneman-2021",
    title: "Noise: A Flaw in Human Judgment",
    by: "Daniel Kahneman, Olivier Sibony & Cass R. Sunstein",
    year: 2021,
  },
  {
    id: "kahneman-2016",
    title: "Noise: How to Overcome the High, Hidden Cost of Inconsistent Decision Making",
    by: "Daniel Kahneman et al., Harvard Business Review",
    year: 2016,
    url: "https://hbr.org/2016/10/noise",
  },
  {
    id: "bhk-2011",
    title: "Strength in Numbers: How Does Data-Driven Decisionmaking Affect Firm Performance?",
    by: "Erik Brynjolfsson, Lorin M. Hitt & Heekyung Hellen Kim, SSRN",
    year: 2011,
    url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1819486",
  },
  {
    id: "brynjolfsson-mcelheran-2016",
    title: "The Rapid Adoption of Data-Driven Decision-Making",
    by: "Erik Brynjolfsson & Kristina McElheran, American Economic Review",
    year: 2016,
    url: "https://doi.org/10.1257/aer.p20161016",
  },
  {
    id: "grove-2000",
    title: "Clinical versus mechanical prediction: A meta-analysis",
    by: "William M. Grove et al., Psychological Assessment",
    year: 2000,
    url: "https://doi.org/10.1037/1040-3590.12.1.19",
  },
  {
    id: "dietvorst-2015",
    title: "Algorithm aversion: People erroneously avoid algorithms after seeing them err",
    by: "Berkeley J. Dietvorst, Joseph P. Simmons & Cade Massey, Journal of Experimental Psychology: General",
    year: 2015,
    url: "https://doi.org/10.1037/xge0000033",
  },
  {
    id: "dietvorst-2018",
    title: "Overcoming Algorithm Aversion: People Will Use Imperfect Algorithms If They Can (Even Slightly) Modify Them",
    by: "Berkeley J. Dietvorst, Joseph P. Simmons & Cade Massey, Management Science",
    year: 2018,
    url: "https://doi.org/10.1287/mnsc.2016.2643",
  },
  {
    id: "wavestone-2024",
    title: "2024 Data and AI Leadership Executive Survey",
    by: "Wavestone",
    year: 2024,
    url: "https://www.wavestone.com/en/insight/data-ai-executive-leadership-survey-2024/",
  },
  // No. 21
  {
    id: "mckinsey-middle-2023",
    title: "Stop wasting your most precious resource: Middle managers",
    by: "McKinsey & Company",
    year: 2023,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/stop-wasting-your-most-precious-resource-middle-managers",
  },
  {
    id: "mollick-2012",
    title: "People and process, suits and innovators: The role of individuals in firm performance",
    by: "Ethan Mollick, Strategic Management Journal",
    year: 2012,
    url: "https://doi.org/10.1002/smj.1958",
  },
  {
    id: "bloomberg-2024",
    title: "Middle Manager Layoffs Surge in US With Firms Questioning Value",
    by: "Bloomberg, Live Data Technologies",
    year: 2024,
    url: "https://www.bloomberg.com/news/articles/2024-03-15/middle-manager-jobs-make-up-30-of-white-collar-layoffs",
  },
  {
    id: "bi-revelio-2024",
    title: "It's a really bad time to be a middle manager",
    by: "Aki Ito, Business Insider, with Revelio Labs",
    year: 2024,
  },
  {
    id: "gartner-2024",
    title: "Gartner Unveils Top Predictions for IT Organizations and Users in 2025 and Beyond",
    by: "Gartner",
    year: 2024,
    url: "https://www.gartner.com/en/newsroom/press-releases/2024-10-22-gartner-unveils-top-predictions-for-it-organizations-and-users-in-2025-and-beyond",
  },
  {
    id: "deloitte-2025",
    title: "Is there still value in the role of managers? Global Human Capital Trends 2025",
    by: "Deloitte",
    year: 2025,
    url: "https://www.deloitte.com/us/en/insights/topics/talent/human-capital-trends/2025/future-of-the-middle-manager.html",
  },
  {
    id: "wooldridge-floyd-1990",
    title: "The strategy process, middle management involvement, and organizational performance",
    by: "Bill Wooldridge & Steven W. Floyd, Strategic Management Journal",
    year: 1990,
    url: "https://ideas.repec.org/a/bla/stratm/v11y1990i3p231-241.html",
  },
];
