// The sources of the weekly Management Review, shared by the issues: an issue names the ones it uses, by id, in
// its own order. Each figure was checked against its source first (docs/revista/management-review-nr-XX.md).
// "via" names the independent summary a figure was checked against when the publisher's own page could not be
// opened; the issue says so beside the source. A source without an address is cited by title and date only.
export const sources = [
  {
    id: "rework-managers",
    title: "Following the data: The research behind great managers",
    by: "Google re:Work",
    year: 2018,
    url: "https://rework.withgoogle.com/intl/en/guides/following-the-data-the-research-behind-great-managers",
  },
  {
    id: "garvin-2013",
    title: "How Google Sold Its Engineers on Management",
    by: "David A. Garvin, Harvard Business Review",
    year: 2013,
    url: "https://hbr.org/2013/12/how-google-sold-its-engineers-on-management",
  },
  {
    id: "bryant-2011",
    title: "Google's Quest to Build a Better Boss",
    by: "Adam Bryant, The New York Times",
    year: 2011,
  },
  {
    id: "quartz-2017",
    title: "Manager feedback at Google: employees are asked 13 questions about their bosses",
    by: "Quartz",
    year: 2017,
    url: "https://qz.com/1058760/manager-feedback-at-google-employees-are-asked-13-questions-about-their-bosses-as-part-of-a-semi-annual-review-goog-googl",
  },
  {
    id: "bock-2015",
    title: "Work Rules!",
    by: "Laszlo Bock",
    year: 2015,
    via: "World Economic Forum, 2015",
    url: "https://www.weforum.org/stories/2015/04/the-9-habits-of-the-best-managers-according-to-googles-hr-boss/",
  },
  {
    id: "gallup-manager-2015",
    title: "State of the American Manager",
    by: "Gallup",
    year: 2015,
    url: "https://www.gallup.com/services/182138/state-american-manager.aspx",
  },
  {
    id: "gallup-rare-2014",
    title: "Why Great Managers Are So Rare",
    by: "Randall Beck & Jim Harter, Gallup",
    year: 2014,
    url: "https://www.gallup.com/workplace/231593/why-great-managers-so-rare.aspx",
  },
  {
    id: "gallup-sogw-2026",
    title: "State of the Global Workplace 2026",
    by: "Gallup",
    year: 2026,
    url: "https://www.gallup.com/workplace/349484/state-of-the-global-workplace.aspx",
  },
  // No. 2
  {
    id: "osha-2019",
    title: "Using Leading Indicators to Improve Safety and Health Outcomes",
    by: "OSHA",
    year: 2019,
    url: "https://www.osha.gov/sites/default/files/OSHA_Leading_Indicators.pdf",
  },
  {
    id: "kaplan-norton-1992",
    title: "The Balanced Scorecard: Measures That Drive Performance",
    by: "Robert S. Kaplan & David P. Norton, Harvard Business Review",
    year: 1992,
  },
  {
    id: "kaplan-norton-1996",
    title: "Using the Balanced Scorecard as a Strategic Management System",
    by: "Robert S. Kaplan & David P. Norton, Harvard Business Review",
    year: 1996,
  },
  {
    id: "mitsmr-bcg-2024",
    title: "The Future of Strategic Measurement: Enhancing KPIs With AI",
    by: "MIT Sloan Management Review & BCG",
    year: 2024,
    url: "https://sloanreview.mit.edu/projects/the-future-of-strategic-measurement-enhancing-kpis-with-ai",
  },
  {
    id: "mitsmr-google-2018",
    title: "Leading With Next-Generation Key Performance Indicators",
    by: "MIT Sloan Management Review & Google",
    year: 2018,
    url: "https://sloanreview.mit.edu/projects/leading-with-next-generation-key-performance-indicators",
  },
  {
    id: "goodhart-1975",
    title: "Problems of Monetary Management: The U.K. Experience",
    by: "Charles Goodhart",
    year: 1975,
  },
  {
    id: "strathern-1997",
    title: "\u2018Improving ratings\u2019: audit in the British University system",
    by: "Marilyn Strathern, European Review",
    year: 1997,
    url: "https://www.cambridge.org/core/journals/european-review/article/improving-ratings-audit-in-the-british-university-system/FC2EE640C0C44E3DB87C29FB666E9AAB",
  },
  // No. 3
  {
    id: "sull-yoder-2018",
    title: "No One Knows Your Strategy \u2014 Not Even Your Top Leaders",
    by: "Charles Sull, Donald Sull & James Yoder, MIT Sloan Management Review",
    year: 2018,
    url: "https://sloanreview.mit.edu/?p=55347",
  },
  {
    id: "sull-homkes-2015",
    title: "Why Strategy Execution Unravels\u2014and What to Do About It",
    by: "Donald Sull, Rebecca Homkes & Charles Sull, Harvard Business Review",
    year: 2015,
    url: "https://hbr.org/2015/03/why-strategy-execution-unravels-and-what-to-do-about-it",
  },
  {
    id: "lbs-2015",
    title: "Two thirds of senior managers can\u2019t name their firm\u2019s top priorities",
    by: "London Business School (Rebecca Homkes & Donald Sull)",
    year: 2015,
    url: "https://www.london.edu/news/two-thirds-of-senior-managers-cant-name-their-firms-top-priorities",
  },
  {
    id: "leinwand-2015",
    title: "Only 8% of Leaders Are Good at Both Strategy and Execution",
    by: "Paul Leinwand, Cesare Mainardi & Art Kleiner, Harvard Business Review",
    year: 2015,
    url: "https://hbr.org/2015/12/only-8-of-leaders-are-good-at-both-strategy-and-execution",
  },
  // No. 4
  {
    id: "edmondson-1999",
    title: "Psychological Safety and Learning Behavior in Work Teams",
    by: "Amy Edmondson, Administrative Science Quarterly",
    year: 1999,
    url: "https://doi.org/10.2307/2666999",
  },
  {
    id: "edmondson-1996",
    title: "Learning from Mistakes Is Easier Said Than Done",
    by: "Amy Edmondson, Journal of Applied Behavioral Science",
    year: 1996,
    url: "https://doi.org/10.1177/0021886396321001",
  },
  {
    id: "rework-teams",
    title: "Understand team effectiveness (Project Aristotle)",
    by: "Google re:Work",
    year: 2015,
    url: "https://rework.withgoogle.com/intl/en/guides/understand-team-effectiveness",
  },
  {
    id: "frazier-2017",
    title: "Psychological Safety: A Meta-Analytic Review and Extension",
    by: "M. Lance Frazier, Stav Fainshmidt, Ryan L. Klinger, Amir Pezeshkan & Veselina Vracheva, Personnel Psychology",
    year: 2017,
    url: "https://doi.org/10.1111/peps.12183",
  },
  {
    id: "mckinsey-2021",
    title: "Psychological safety and the critical role of leadership development",
    by: "McKinsey & Company",
    year: 2021,
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/psychological-safety-and-the-critical-role-of-leadership-development",
  },
  {
    id: "edmondson-2018",
    title: "The Fearless Organization",
    by: "Amy C. Edmondson",
    year: 2018,
  },
  // No. 5
  {
    id: "ohno-1988",
    title: "Toyota Production System: Beyond Large-Scale Production",
    by: "Taiichi Ohno",
    year: 1988,
  },
  {
    id: "lei-lexicon",
    title: "Lean Lexicon: seven wastes",
    by: "Lean Enterprise Institute",
    year: 2014,
    url: "https://www.lean.org/lexicon-terms/seven-wastes/",
  },
  {
    id: "lei-eight-wastes",
    title: "The Eight Wastes of Lean",
    by: "Lean Enterprise Institute, The Lean Post",
    year: 2020,
    url: "https://www.lean.org/the-lean-post/articles/the-eight-wastes-of-lean/",
  },
  {
    id: "liker-2004",
    title: "The Toyota Way",
    by: "Jeffrey K. Liker",
    year: 2004,
  },
  {
    id: "womack-jones-1996",
    title: "Lean Thinking",
    by: "James P. Womack & Daniel T. Jones",
    year: 1996,
    via: "Lean Enterprise Institute, Seeing the Whole",
    url: "https://www.lean.org/wp-content/uploads/2021/01/seeing-the-whole-introduction.pdf",
  },
  {
    id: "krafcik-1988",
    title: "Triumph of the Lean Production System",
    by: "John F. Krafcik, Sloan Management Review",
    year: 1988,
  },
  {
    id: "womack-1990",
    title: "The Machine That Changed the World",
    by: "James P. Womack, Daniel T. Jones & Daniel Roos",
    year: 1990,
  },
];
